version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    container_name: zookeeper
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "my_topic:1:3"
  app-a:
    build: appA/.
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8080:8080"
  app-b:
    build: appB/.
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8081:8080"