server:
  port: 8080
spring:
  kafka:
    producer:
      bootstarp-servers: locahost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
